# Generated by Django 4.2.5 on 2023-10-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElectricityForecaster", "0003_practiceactuals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Errors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "mae",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "mape",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "rmse",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "errors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pracpredictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "load",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pracpredictions",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="PracticeActuals",
        ),
        migrations.DeleteModel(
            name="PracticePredictions",
        ),
    ]
