# Generated by Django 4.2.5 on 2023-09-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElectricityForecaster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticePredictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "load",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pracpredictions",
                "managed": False,
            },
        ),
    ]
